version = 1

[install]
go.pkg-path = "go"
go.version = "^1.23"

[hook]
on-activate = """
  # Point GOENV to Flox environment cache
  export GOENV="$FLOX_ENV_CACHE/goenv"

  # Install Go dependencies
  go mod tidy

  # Install CI tools
  go install golang.org/x/lint/golint@latest
  go install honnef.co/go/tools/cmd/staticcheck@latest
  go install github.com/client9/misspell/cmd/misspell@latest
"""

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
